package BoxeeKey;

# Taken from XBMC Key.h

$KEYS = {
    ACTION_MOVE_LEFT => 272,
    ACTION_MOVE_RIGHT => 273,
    ACTION_MOVE_UP => 270,
    ACTION_MOVE_DOWN => 271,
    ACTION_START => 100,
    ACTION_BACK => 110,
    ACTION_BUTTON_A => 256,
    ACTION_BUTTON_B => 257,
    ACTION_PLAY => 79,
    ACTION_VOLUME_UP => 88,
    ACTION_VOLUME_DOWN => 89,
    ACTION_MUTE => 91,
    ACTION_PAUSE => 12,
    ACTION_STOP => 13,
};
sub keys { $KEYS }

1;
