package BoxeeKey;

# Taken from XBMC Key.h

$KEYS = (
    ACTION_NONE => 0
    ACTION_MOVE_LEFT => 1
    ACTION_MOVE_RIGHT => 2
    ACTION_MOVE_UP => 3
    ACTION_MOVE_DOWN => 4
    ACTION_PAGE_UP => 5
    ACTION_PAGE_DOWN => 6
    ACTION_SELECT_ITEM => 7
    ACTION_HIGHLIGHT_ITEM => 8
    ACTION_PARENT_DIR => 9
    ACTION_PREVIOUS_MENU => 10
    ACTION_SHOW_INFO => 11
    ACTION_PAUSE => 12
    ACTION_STOP => 13
    ACTION_NEXT_ITEM => 14
    ACTION_PREV_ITEM => 15
);

1;
